# -*- coding: utf-8 -*-
"""DataCleanCode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CN4Nr1h_dnQzIT8s5xAkaRYpEULSSr-o
"""

pip install face_recognition

# General ML imports
import numpy as np
import pandas as pd
import sklearn as sk

# NN imports
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# Displaying images imports
import matplotlib.pyplot as plt

# Image parsing imports
from PIL import Image
from IPython.display import display

import random
import os
from collections import Counter

import kagglehub

# Face recognition import for cropping faces
import face_recognition

def getFace(img_path):
    global numSkipped
    image = face_recognition.load_image_file(img_path)

    face_locations = face_recognition.face_locations(image) # Face cropping lib

    if len(face_locations) == 0: # If no face was found
        return None

    top, right, bottom, left = face_locations[0]
    if (bottom - top) < 128 or (right - left) < 128: # Minimum resolution is 128x128
      return None

    face_image = image[top:bottom, left:right]
    pil_image = Image.fromarray(face_image)

    width, height = pil_image.size
    new_width, new_height = 128, 128

    # Crop to center of image
    crop_left = (width - new_width) // 2
    crop_top = (height - new_height) // 2
    crop_right = crop_left + new_width
    crop_bottom = crop_top + new_height
    center_cropped = pil_image.crop((crop_left, crop_top, crop_right, crop_bottom))

    return center_cropped

getFace(img_path)

print("Loading real images")
realImages = getImagesFromPath("real_vs_fake/real-vs-fake/train/real", 50000)
print("Done with 50000/70000")
realImages.extend(getImagesFromPath("real_vs_fake/real-vs-fake/test/real", 10000))
print("Done with 60000/70000")
realImages.extend(getImagesFromPath("real_vs_fake/real-vs-fake/valid/real", 10000))
print("Done with 70000/70000")

realImagesWithLabel = [[img, 0] for img in realImages] # Label as real image
print("Success loading real images")

print("Loading fake images")
fakeImages = getImagesFromPath("real_vs_fake/real-vs-fake/train/fake", 50000)
print("Done with 50000/70000 2")
fakeImages.extend(getImagesFromPath("real_vs_fake/real-vs-fake/test/fake", 10000))
print("Done with 60000/70000 2")
fakeImages.extend(getImagesFromPath("real_vs_fake/real-vs-fake/valid/fake", 10000))
print("Done with 70000/70000 2")

fakeImagesWithLabel = [[img, 1] for img in fakeImages] # Label as AI
print("Success loading fake images")

import zipfile, io

# save to colab local disk first
with zipfile.ZipFile('/content/real_images.zip', 'w') as zf:
    for i, (img, label) in enumerate(realImagesWithLabel):
        buf = io.BytesIO()
        img.save(buf, format='JPEG', quality=95)
        zf.writestr(f'real/{i:06d}.jpg', buf.getvalue())
        if i % 5000 == 0:
            print(f"{i}/70000 saved...")

print("Done — starting download")

# then download to your computer
from google.colab import files
files.download('/content/real_images.zip')

!unzip /content/real_images.zip -d /content/data/
!unzip /content/fake.zip -d /content/data/

paths  = [f'/content/data/real/{i:06d}.jpg' for i in range(69500)]
labels = [0] * 69500

paths  += [f'/content/data/fake/{i:06d}.jpg' for i in range(69500)]
labels += [1] * 69500