# -*- coding: utf-8 -*-
"""ML_Final_Work_Patches.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RjT51pGBsrTtS_7srnr3ny45OVptJjZA

###Imports:
"""

pip install face_recognition

# General ML imports
import numpy as np
import pandas as pd
import sklearn as sk
from sklearn.model_selection import train_test_split

# NN imports
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms

# Displaying images imports
import matplotlib.pyplot as plt

# Image parsing imports
from PIL import Image
from IPython.display import display

import random
import os
from collections import Counter
import time
import kagglehub

# Face recognition import for cropping faces
import face_recognition

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

"""###Load Data:"""

!unzip /content/real_images.zip -d /content/data/
!unzip /content/fake_images.zip -d /content/data/

paths  = [f'/content/data/real/{i:06d}.jpg' for i in range(69500)]
labels = [0] * 69500

paths  += [f'/content/data/fake/{i:06d}.jpg' for i in range(69500)]
labels += [1] * 69500

"""###Train, Validation, Test Split:"""

# First split: train vs (val + test)
X_train, X_temp, y_train, y_temp = train_test_split(
    paths, labels,
    test_size=0.2,
    stratify=labels,
    random_state=42
)

# Second split: validation vs test
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp,
    test_size=0.5,
    stratify=y_temp,
    random_state=42
)

class GridPatchDataset(Dataset):
    def __init__(self, image_paths, labels, patch_size):
        self.paths      = image_paths
        self.labels     = labels
        self.patch_size = patch_size
        self.img_size   = 128
        self.grid       = self.img_size // patch_size

        self.transform = transforms.Compose([
            transforms.ToTensor()
        ])

        self.index = [  # Index: indexs to the particular patch
            (img_idx, r, c)
            for img_idx in range(len(image_paths))
            for r in range(self.grid)
            for c in range(self.grid)
        ]

    def __len__(self):
        return len(self.index)

    def __getitem__(self, idx):
        img_idx, r, c = self.index[idx]
        ps = self.patch_size

        img = Image.open(self.paths[img_idx]).convert('RGB')
        left, upper = c * ps, r * ps
        patch = img.crop((left, upper, left + ps, upper + ps))

        return self.transform(patch), self.labels[img_idx], img_idx

"""###Dataloader Initialization:"""

batch_size = 1024
patch_size = 16

# Training Data
trainingData16 = GridPatchDataset(X_train, y_train, patch_size)
train_dataloader16 = DataLoader(trainingData16, batch_size=batch_size, shuffle=True, num_workers=8)

# Validation Data
valData16 = GridPatchDataset(X_val, y_val, patch_size)
val_dataloader16 = DataLoader(valData16, batch_size=batch_size, shuffle=True, num_workers=8)

# Test Data
testData16 = GridPatchDataset(X_test, y_test, patch_size)
test_dataloader16 = DataLoader(testData16, batch_size=batch_size, shuffle=True, num_workers=8)

batch_size = 256
patch_size = 32

# Training Data
trainingData32 = GridPatchDataset(X_train, y_train, patch_size)
train_dataloader32 = DataLoader(trainingData32, batch_size=batch_size, shuffle=True, num_workers=8)

# Validation Data
valData32 = GridPatchDataset(X_val, y_val, patch_size)
val_dataloader32 = DataLoader(valData32, batch_size=batch_size, shuffle=True, num_workers=8)

# Test Data
testData32 = GridPatchDataset(X_test, y_test, patch_size)
test_dataloader32 = DataLoader(testData32, batch_size=batch_size, shuffle=True, num_workers=8)

batch_size = 64
patch_size = 64

# Training Data
trainingData64 = GridPatchDataset(X_train, y_train, patch_size)
train_dataloader64 = DataLoader(trainingData64, batch_size=batch_size, shuffle=True, num_workers=8)

# Validation Data
valData64 = GridPatchDataset(X_val, y_val, patch_size)
val_dataloader64 = DataLoader(valData64, batch_size=batch_size, shuffle=True, num_workers=8)

# Test Data
testData64 = GridPatchDataset(X_test, y_test, patch_size)
test_dataloader64 = DataLoader(testData64, batch_size=batch_size, shuffle=True, num_workers=8)

batch_size = 16
patch_size = 128

# Training Data
trainingData128 = GridPatchDataset(X_train, y_train, patch_size)
train_dataloader128 = DataLoader(trainingData128, batch_size=batch_size, shuffle=True, num_workers=8)

# Validation Data
valData128 = GridPatchDataset(X_val, y_val, patch_size)
val_dataloader128 = DataLoader(valData128, batch_size=batch_size, shuffle=True, num_workers=8)

# Test Data
testData128 = GridPatchDataset(X_test, y_test, patch_size)
test_dataloader128 = DataLoader(testData128, batch_size=batch_size, shuffle=True, num_workers=8)

# Dataloaders, change depending on what size patch,
# we are training the model on.
currentPatchSize = 64
currentTrainDataLoader = train_dataloader64
currentValDataLoader = val_dataloader64
currentTestDataLoader = test_dataloader64

"""###**Naive Neural Network**:

*   Fully Connected layers implementation
"""

class NaiveNeuralNetwork(nn.Module):
    def __init__(self):
        super(NaiveNeuralNetwork, self).__init__()
        #input size for RBG images is 32 * 32 * 3
        self.fc1 = nn.Linear(32 * 32 * 3, 256)
        self.fc2 = nn.Linear(256,128)
        self.fc3 = nn.Linear(128,64)
        self.fc4 = nn.Linear(64, 32)
        self.fc5 = nn.Linear(32,16)
        self.fc6 = nn.Linear(16,2) # output layer(binary classification)


    def forward(self, x):
       #flatten the image
       x = x.view(-1 , 32 * 32 * 3)
       #relu activation
       x = F.relu(self.fc1(x))
       x = F.relu(self.fc2(x))
       x = F.relu(self.fc3(x))
       x = F.relu(self.fc4(x))
       x = F.relu(self.fc5(x))
       x = self.fc6(x) #output
       return x

naive_model = NaiveNeuralNetwork().to(device)
naive_criterion = torch.nn.CrossEntropyLoss()
naive_optimizer = optim.Adam(naive_model.parameters(), lr=0.001)


start = time.time() # seconds since epoch

# Training loop
for epoch in range(1):
    naive_model.train()
    total_loss = 0
    num_batches = 0

    for batch in currentTrainDataLoader:
        xTensor = batch[0].to(device)
        yTensor = batch[1].to(device)
        naive_optimizer.zero_grad()
        preds = naive_model(xTensor)
        loss = naive_criterion(preds, yTensor)
        loss.backward()
        naive_optimizer.step()

        total_loss += loss.item()
        num_batches += 1

    avg_loss = total_loss / num_batches
    print(f"Epoch {epoch+1}, Loss: {avg_loss:.4f}")

end = time.time()
print(f"Elapsed time: {end - start:.2f} seconds")

"""### Naive NN Model Testing:"""

# Validation set accuracy:
naive_model.eval()

test_loss = 0
correct   = 0
num_batches = 0

with torch.no_grad():
    for batch in currentValDataLoader:
        xTensor = batch[0].to(device)
        yTensor = batch[1].to(device)

        preds = naive_model(xTensor)
        loss  = naive_criterion(preds, yTensor)
        test_loss  += loss.item()
        num_batches += 1

        predicted_labels = preds.argmax(dim=1)
        correct += (predicted_labels == yTensor).sum().item()

avg_val_loss = test_loss / num_batches
accuracy     = correct / len(currentValDataLoader.dataset)
print(f"Val Loss: {avg_val_loss:.4f}, Accuracy: {accuracy:.4f}")

# Test accuracy
naive_model.eval() #set model to eval mode

test_loss   = 0
correct     = 0
num_batches = 0

with torch.no_grad():
    for batch in currentTestDataLoader:
        xTensor = batch[0].to(device)
        yTensor = batch[1].to(device)

        preds = naive_model(xTensor)
        loss  = naive_criterion(preds, yTensor)
        test_loss  += loss.item()
        num_batches += 1

        predicted_labels = preds.argmax(dim=1)
        correct += (predicted_labels == yTensor).sum().item()

avg_test_loss = test_loss / num_batches
accuracy      = correct / len(currentTestDataLoader.dataset)

print(f"Test Loss: {avg_test_loss:.4f}, Accuracy: {accuracy:.4f}")

naive_model.eval() #set model to evaluation mode

test_loss   = 0
correct     = 0
num_batches = 0

with torch.no_grad():
    for batch in currentTrainDataLoader:
        xTensor = batch[0].to(device)
        yTensor = batch[1].to(device)

        preds = naive_model(xTensor)
        loss  = naive_criterion(preds, yTensor)
        test_loss  += loss.item()
        num_batches += 1

        predicted_labels = preds.argmax(dim=1)
        correct += (predicted_labels == yTensor).sum().item()

avg_train_loss = test_loss / num_batches
accuracy       = correct / len(currentTrainDataLoader.dataset)
print(f"Train Loss: {avg_train_loss:.4f}, Accuracy: {accuracy:.4f}")

def getNaiveAggregatedAccuracy(): # Aggregated image-level accuracy
    num_images   = 0
    correctCount = 0

    for img_idx in range(len(X_test)):
        image   = Image.open(X_test[img_idx])
        patches = getTensorPatches(image)

        with torch.no_grad():
            preds            = naive_model(patches)
            predicted_labels = preds.argmax(dim=1)

        if sum(predicted_labels) >= len(predicted_labels) // 2:
            decisionClass = 1
        else:
            decisionClass = 0

        if decisionClass == y_test[img_idx]:
            correctCount += 1

        num_images += 1

    print(f"Total Correct: {correctCount} over {num_images} images")
    print(f"Accuracy {(correctCount / num_images) * 100:.2f}%")

getNaiveAggregatedAccuracy()

"""###**Convolutional Neural Network:**"""

class ConvolutionalNeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 32, 3, 1, padding=1)
        self.bn1 = nn.BatchNorm2d(32)
        self.conv2 = nn.Conv2d(32, 64, 3, 1, padding=1)
        self.bn2 = nn.BatchNorm2d(64)
        self.conv3 = nn.Conv2d(64, 128, 3, 1, padding=1)
        self.bn3 = nn.BatchNorm2d(128)
        self.pool = nn.MaxPool2d(2)
        self.global_pool = nn.AdaptiveAvgPool2d((1, 1))
        self.fc1 = nn.Linear(128, 64)
        self.fc2 = nn.Linear(64, 2)
        self.dropout = nn.Dropout(0.5)

    def forward(self, x):
        x = F.relu(self.bn1(self.conv1(x)))
        x = self.pool(F.relu(self.bn2(self.conv2(x))))
        x = F.relu(self.bn3(self.conv3(x)))
        x = self.global_pool(x)
        x = torch.flatten(x, 1)
        x = self.dropout(F.relu(self.fc1(x)))
        x = self.fc2(x)
        return x

model = ConvolutionalNeuralNetwork().to(device)
criterion = torch.nn.CrossEntropyLoss()  # Cross-Entropy Loss is standard for CNN
optimizer = optim.Adam(model.parameters(), lr=0.001) # Defaul LR for Adam optimizer is .001

"""###Model Training:"""

start = time.time()  # seconds since epoch

for epoch in range(1): # Training Loop:
    model.train()
    total_loss = 0
    num_batches = 0

    for batch in currentTrainDataLoader:
        xTensor = batch[0].to(device)
        yTensor = batch[1].to(device)
        optimizer.zero_grad()
        preds = model(xTensor)
        loss = criterion(preds, yTensor)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        num_batches += 1

    avg_loss = total_loss / num_batches
    print(f"Epoch {epoch+1}, Loss: {avg_loss:.4f}")

end = time.time()
elapsed = end - start
print(f"Elapsed time: {elapsed:.2f} seconds")

"""###Model Testing:"""

# Test Model accuracy on validation set:
model.eval() # Set model to evaluation mode

test_loss = 0
correct = 0
num_batches = 0

with torch.no_grad():  # disable gradients for evaluation
    for batch in currentValDataLoader:
        xTensor = batch[0].to(device)
        yTensor = batch[1].to(device)

        preds = model(xTensor)
        loss = criterion(preds, yTensor)
        test_loss += loss.item()
        num_batches += 1

        predicted_labels = preds.argmax(dim=1)
        correct += (predicted_labels == yTensor).sum().item()

avg_test_loss = test_loss / num_batches
accuracy = correct / len(currentValDataLoader.dataset)

print(f"Val Loss: {avg_test_loss:.4f}, Accuracy: {accuracy:.4f}")

# Test Model accuracy on Test set:
model.eval() # Set model to evaluation mode

test_loss = 0
correct = 0
num_batches = 0

with torch.no_grad():  # disable gradients for evaluation
    for batch in currentTestDataLoader:
        xTensor = batch[0].to(device)
        yTensor = batch[1].to(device)

        preds = model(xTensor)
        loss = criterion(preds, yTensor)
        test_loss += loss.item()
        num_batches += 1

        predicted_labels = preds.argmax(dim=1)
        correct += (predicted_labels == yTensor).sum().item()

avg_test_loss = test_loss / num_batches
accuracy = correct / len(currentTestDataLoader.dataset)

print(f"Test Loss: {avg_test_loss:.4f}, Accuracy: {accuracy:.4f}")

# Test Model accuracy on Train set:
model.eval() # Set model to evaluation mode

test_loss = 0
correct = 0
num_batches = 0

with torch.no_grad():  # disable gradients for evaluation
    for batch in currentTrainDataLoader:
        xTensor = batch[0].to(device)
        yTensor = batch[1].to(device)

        preds = model(xTensor)
        loss = criterion(preds, yTensor)
        test_loss += loss.item()
        num_batches += 1

        predicted_labels = preds.argmax(dim=1)
        correct += (predicted_labels == yTensor).sum().item()

avg_test_loss = test_loss / num_batches
accuracy = correct / len(currentTrainDataLoader.dataset)

print(f"Train Loss: {avg_test_loss:.4f}, Accuracy: {accuracy:.4f}")

"""###Data Visualization:"""

def highlight(image, ps, probs):
    highlight_color_fake = (255, 80, 80)   # red
    highlight_color_real = (80, 255, 120)  # green`

    patchIdx = 0
    for i in range(ps, image.width+1, ps):
      for j in range(ps, image.height+1, ps):
        box = (i-ps, j-ps, i, j)
        region = image.crop(box)
        if probs[patchIdx][0] > probs[patchIdx][1]:
          highlight = Image.new(region.mode, region.size, highlight_color_real)
        else:
          highlight = Image.new(region.mode, region.size, highlight_color_fake)

        region = Image.blend(region, highlight, probs[patchIdx][1])
        image.paste(region, box)
        patchIdx += 1

    display(image)

def getPatches(image, ps):
    retPatchArr = []
    for i in range(0, image.width, ps):
        for j in range(0, image.height, ps):
            box = (i, j, i + ps, j + ps)
            patch = image.crop(box)
            retPatchArr.append(np.array(patch, dtype=np.float32))
    return np.array(retPatchArr) / 255 # Normalize


def getTensorPatches(image):
  transform = transforms.Compose([
              transforms.ToTensor()
          ])

  patches = getPatches(image, currentPatchSize)
  patches = [transform(p).to(device) for p in patches]
  patches = torch.stack(patches)

  return patches

def getAggregatedAccuracy(): # Accuracy based on all patches of an image
    num_images = 0
    correctCount = 0

    for img_idx in range(len(X_test)):
        image = X_test[img_idx]
        image = Image.open(image)
        patches = getTensorPatches(image)

        with torch.no_grad():  # disable gradients for evaluation
          preds = model(patches)
          predicted_labels = preds.argmax(dim=1)

        # Aggregate simply on higher proportion of patch labels
        if sum(predicted_labels) >= len(predicted_labels) // 2:
          decisionClass = 1
        else: decisionClass = 0

        trueLabel = y_test[img_idx]
        if decisionClass == trueLabel:
          correctCount += 1

        num_images += 1

    print(f"Total Correct: {correctCount} over {num_images} images")
    print(f"Accuracy {(correctCount / num_images) * 100:.2f}%")

getAggregatedAccuracy()

# Red is estimated as AI generated
# Green is estimated as real
# Darker is higher estimated probability
def getProbHeatMap(testImageIdx):
  image = X_test[testImageIdx]
  image = Image.open(image)
  patches = getTensorPatches(image)

  trueLabel = y_test[testImageIdx]

  logits = []
  with torch.no_grad(): # disable gradients for evaluation
      pred = model(patches)
      logits.append(pred)

  logits_tensor = torch.cat(logits, dim=0)

  temperature = 2 # Temperature scaling
  probs = F.softmax(logits_tensor / temperature, dim=1)
  probs_list = probs.tolist()

  decisions = logits_tensor.argmax(dim=1)
  if sum(decisions) >= len(decisions) // 2:
    decisionClass = 1
  else: decisionClass = 0

  print(f"True label: {trueLabel}")
  print(f"Predicted label: {decisionClass}")

  highlight(image, currentPatchSize, probs_list)

getProbHeatMap(125)

"""###Saving and Loading Model:"""

torch.save(model.state_dict(), "model.pth") # Save model

# To load models
loadedModel = ConvolutionalNeuralNetwork().to(device)
loadedModel.load_state_dict(torch.load("model128-1.pth"))
